[build]
  publish = "web"
  command = "echo 'Production build ready'"

[[redirects]]
  from = "/production"
  to = "/production.html"
  status = 200

[[redirects]]
  from = "/unreal"
  to = "/unreal.html"
  status = 200

[[redirects]]
  from = "/game"
  to = "/game.html"
  status = 200

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.data"
  [headers.values]
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
